# This playbook contains example tasks to perform on a fresh Fedora
# installation. 
#
# Copyright (c) 2013-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook setup.yml -f 10

---
- hosts: localhost
  connection: local
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive.yml

  tasks:
    - include: tasks/preparation.yml  
    - include: tasks/yum.repos.yml  
#    - include: tasks/gh.repos.yml  
    - include: tasks/packages.yml  
    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
