# This playbook remove all components which were needed for the setup. 
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload
