# This playbook install the bootstrap (http://twitter.github.com/bootstrap/)
# javascript framework.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: download the bootstrap zip archive
  get_url: url=https://github.com/twbs/bootstrap/releases/download/v{{ bootstrap_version }}/bootstrap-{{ bootstrap_version }}-dist.zip
           dest=/var/www/lighttpd/bootstrap.zip
           mode=0644

- name: unpack the bootstrap archive
  command: /usr/bin/unzip -o /var/www/lighttpd/bootstrap.zip -d /var/www/lighttpd/

- name: rename the created folder
  command: /usr/bin/mv /var/www/lighttpd/dist /var/www/lighttpd/bootstrap

- name: delete the bootstrap archive
  file: path=/var/www/lighttpd/bootstrap.zip
        state=absent

- name: install a default index.html file
  template: src=files/bootstrap.j2
            dest=/var/www/lighttpd/index.html
            owner=root
            group=root
            mode=0755

- name: remove lighttpd default file (images)
  file: path=/var/www/lighttpd/{{ item }}
        state=absent
  with_items:
    - light_logo.png
    - favicon.ico
    - light_button.png
    - poweredby.png
