# This playbook install all needed components for the setup.
#
# Copyright (c) 2013-2015 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install packages
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - VirtualBox
      - WoeUSB
      - ack
      - amule
      - asciinema
      - banner
      - baobab
      - bash-completion
      - bcompare
      - bjnplugin
      - boxes
      - buildah
      - calibre
      - california
      - ccze
      - chromium-freeworld
      - chromium-freeworld-libs
      - chromium-freeworld-libs-media
      - chromium-pepper-flash
      - chromium-widevine
      - code
      - curl
      - dnsmasq
      - docker
      - easystroke
      - ffmpeg
      - fpaste
      - fuse
      - fuse-sshfs
      - gcc
      - gimp
      - git
      - glusterfs
      - golang
      - google-chrome-stable
      - gstreamer
      - gtk3
      - hdf5
      - htop
      - hub
      - iotop
      - iptables
      - jad
      - java-9-openjdk
      - jq
      - kernel-devel
      - kmod
      - libreoffice
      - lsof
      - make
      - meld
      - mosh
      - nemo
      - ngrep
      - nmap
      - ntfs-3g
      - oathtool
      - openh264
      - openvpn
      - origin
      - origin-clients
      - p7zip
      - perf
      - perl
      - qpdf
      - rest
      - rsync
      - ruby
      - samba-client
      - screen
      - shutter
      - simplescreenrecorder
      - socat
      - sshpass
      - ssmtp
      - strace
      - stress
      - subversion
      - tcping
      - terminator
      - the_silver_searcher
      - tcping
      - tig
      - tilix
      - tmux
      - traceroute
      - unrar
      - vim-minimal
      - virt-manager
      - vlc
      - wget
      - which
      - wireshark
      - x264
      - zsh
      - https://www.r-studio.com/downloads/RStudio4_x64.rpm

