# This playbook install all needed components for the setup.
#
# Copyright (c) 2013-2015 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: update all packages
  dnf:
    name: "*"
    state: latest
- name: Install roles from Ansible Galaxy
  command: ansible-galaxy install -v -p /usr/share/ansible/roles {{ item }}
  with_items:
    - "{{ ansible_roles }}"
