---
- name: Invoke Visual Studio Code Extensions installer
  include_role:
    name: ansible-role-visual-studio-code-extensions
  vars:
    users:
      - username: pantinor
        visual_studio_code_extensions: "{{ vscode_extensions }}"

- name: Invoke Gnome Extensions installer
  include_role:
    name: ansible-gnome-extensions
  vars:
    gnome_extensions_ids: "{{ gnome_extensions_ids }}"          